In [2]:
import pandas as pd
import glob, os
#os.chdir("All_Listings/")

import numpy as np
#!pip install --upgrade pip
#!pip install gender-guesser

import gender_guesser.detector as gender

# Combine All Listing Data

In [2]:
Combined = pd.DataFrame()
counter = 0

for file in glob.glob("All_Data/All_Listings/*.csv.gz"):
    
    counter = counter + 1
    print('********   City ',counter,':',  file)
    data = pd.read_csv(file, compression='gzip', error_bad_lines=False)
    print('Shape of file:', data.shape)
    Combined = Combined.append(data)
    print('Shape of Combined:',Combined.shape)
    
print('*************************')

Combined_Listings = Combined.to_csv ('Combined_Listings.csv.gz', index = None, header=True, compression='gzip')

print('Shape of Combined:',Combined.shape)

for index, col in enumerate(Combined.columns): 
    print(index, col)

********   City  1 : All_Data/All_Listings/Chicago_listings.csv.gz

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (61,62) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

Shape of file: (8533, 106)
Shape of Combined: (8533, 106)
********   City  2 : All_Data/All_Listings/Cambridge_listings.csv.gz
Shape of file: (1277, 106)
Shape of Combined: (9810, 106)
********   City  3 : All_Data/All_Listings/RhodeIsland_listings.csv.gz
Shape of file: (3876, 106)
Shape of Combined: (13686, 106)
********   City  4 : All_Data/All_Listings/Denver_listings.csv.gz
Shape of file: (4865, 106)
Shape of Combined: (18551, 106)
********   City  5 : All_Data/All_Listings/SanDiego_listings.csv.gz

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (43,94) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

Shape of file: (13574, 106)
Shape of Combined: (32125, 106)
********   City  6 : All_Data/All_Listings/PacificGrove_listings.csv.gz
Shape of file: (218, 106)
Shape of Combined: (32343, 106)
********   City  7 : All_Data/All_Listings/Seattle_listings.csv.gz

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (43,61,62) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

Shape of file: (9023, 106)
Shape of Combined: (41366, 106)
********   City  8 : All_Data/All_Listings/SanMateo_listings.csv.gz
Shape of file: (7, 106)
Shape of Combined: (41373, 106)
********   City  9 : All_Data/All_Listings/Broward_listings.csv.gz
Shape of file: (10325, 106)
Shape of Combined: (51698, 106)
********   City  10 : All_Data/All_Listings/Salem_listings.csv.gz
Shape of file: (197, 106)
Shape of Combined: (51895, 106)
********   City  11 : All_Data/All_Listings/Boston_listings.csv.gz
Shape of file: (3507, 106)
Shape of Combined: (55402, 106)
********   City  12 : All_Data/All_Listings/Washington_listings.csv.gz
Shape of file: (9152, 106)
Shape of Combined: (64554, 106)
********   City  13 : All_Data/All_Listings/Austin_listings.csv.gz
Shape of file: (11250, 106)
Shape of Combined: (75804, 106)
********   City  14 : All_Data/All_Listings/Oakland_listings.csv.gz
Shape of file: (3350, 106)
Shape of Combined: (79154, 106)
********   City  15 : All_Data/All_Listings/NewYork_listings.csv.gz

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (61,62,94,95) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

Shape of file: (50599, 106)
Shape of Combined: (129753, 106)
********   City  16 : All_Data/All_Listings/Columbus_listings.csv.gz
Shape of file: (1411, 106)
Shape of Combined: (131164, 106)
********   City  17 : All_Data/All_Listings/Portland_listings.csv.gz
Shape of file: (4793, 106)
Shape of Combined: (135957, 106)
********   City  18 : All_Data/All_Listings/Asheville_listings.csv.gz
Shape of file: (2441, 106)
Shape of Combined: (138398, 106)
********   City  19 : All_Data/All_Listings/SantaClara_listings.csv.gz
Shape of file: (7658, 106)
Shape of Combined: (146056, 106)
********   City  20 : All_Data/All_Listings/Jersey_listings.csv.gz
Shape of file: (3103, 106)
Shape of Combined: (149159, 106)
********   City  21 : All_Data/All_Listings/SantaCruz_listings.csv.gz
Shape of file: (1791, 106)
Shape of Combined: (150950, 106)
********   City  22 : All_Data/All_Listings/Hawaii_listings.csv.gz

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (61,62,95) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

Shape of file: (23745, 106)
Shape of Combined: (174695, 106)
********   City  23 : All_Data/All_Listings/TwinCities_listings.csv.gz
Shape of file: (6900, 106)
Shape of Combined: (181595, 106)
********   City  24 : All_Data/All_Listings/NewOrleans_listings.csv.gz
Shape of file: (6520, 106)
Shape of Combined: (188115, 106)
********   City  25 : All_Data/All_Listings/LosAngeles_listings.csv.gz
Shape of file: (40125, 106)
Shape of Combined: (228240, 106)
********   City  26 : All_Data/All_Listings/Nashville_listings.csv.gz
Shape of file: (7396, 106)
Shape of Combined: (235636, 106)
********   City  27 : All_Data/All_Listings/SanFrancisco_listings.csv.gz
Shape of file: (8533, 106)
Shape of Combined: (244169, 106)
********   City  28 : All_Data/All_Listings/ClarkCounty_listings.csv.gz
Shape of file: (10492, 106)
Shape of Combined: (254661, 106)
*************************
Shape of Combined: (254661, 106)
0 id
1 listing_url
2 scrape_id
3 last_scraped
4 name
5 summary
6 space
7 description
8 experiences_offered
9 neighborhood_overview
10 notes
11 transit
12 access
13 interaction
14 house_rules
15 thumbnail_url
16 medium_url
17 picture_url
18 xl_picture_url
19 host_id
20 host_url
21 host_name
22 host_since
23 host_location
24 host_about
25 host_response_time
26 host_response_rate
27 host_acceptance_rate
28 host_is_superhost
29 host_thumbnail_url
30 host_picture_url
31 host_neighbourhood
32 host_listings_count
33 host_total_listings_count
34 host_verifications
35 host_has_profile_pic
36 host_identity_verified
37 street
38 neighbourhood
39 neighbourhood_cleansed
40 neighbourhood_group_cleansed
41 city
42 state
43 zipcode
44 market
45 smart_location
46 country_code
47 country
48 latitude
49 longitude
50 is_location_exact
51 property_type
52 room_type
53 accommodates
54 bathrooms
55 bedrooms
56 beds
57 bed_type
58 amenities
59 square_feet
60 price
61 weekly_price
62 monthly_price
63 security_deposit
64 cleaning_fee
65 guests_included
66 extra_people
67 minimum_nights
68 maximum_nights
69 minimum_minimum_nights
70 maximum_minimum_nights
71 minimum_maximum_nights
72 maximum_maximum_nights
73 minimum_nights_avg_ntm
74 maximum_nights_avg_ntm
75 calendar_updated
76 has_availability
77 availability_30
78 availability_60
79 availability_90
80 availability_365
81 calendar_last_scraped
82 number_of_reviews
83 number_of_reviews_ltm
84 first_review
85 last_review
86 review_scores_rating
87 review_scores_accuracy
88 review_scores_cleanliness
89 review_scores_checkin
90 review_scores_communication
91 review_scores_location
92 review_scores_value
93 requires_license
94 license
95 jurisdiction_names
96 instant_bookable
97 is_business_travel_ready
98 cancellation_policy
99 require_guest_profile_picture
100 require_guest_phone_verification
101 calculated_host_listings_count
102 calculated_host_listings_count_entire_homes
103 calculated_host_listings_count_private_rooms
104 calculated_host_listings_count_shared_rooms
105 reviews_per_month

# Add Gender to Host Names

In [3]:
Combined = pd.read_csv('Combined_Listings.csv.gz', compression='gzip', error_bad_lines=False, low_memory=False)

Combined['host_name_has_space'] = np.where(Combined['host_name'].str.contains(' ') , 1, 0)

d = gender.Detector()
Combined['host_gender'] = Combined['host_name'].apply(d.get_gender)

#Combined['gender'] = Combined['host_name'].apply(d.get_gender, 'usa') ### doesn't make a difference

Combined.loc[Combined['host_name_has_space'] == 1, 'host_gender'] = 'not_a_name'

#print(host)
#Host = host.to_csv ('Host_Name.csv', index = None, header=True)

# Rearrange Columns and Save Data

In [4]:
cols = Combined.columns.tolist()
cols = cols[:22] + cols [-2:] + cols[22:-2]
Combined = Combined[cols]

np.savetxt('Columns_Listings.csv', np.asarray(cols),  delimiter=",", fmt="%s")

#for index, col in enumerate(Combined.columns): 
#    print(index, col)
    
Combined_Listings = Combined.to_csv ('Combined_Listings_Gendered.csv.gz', index = None, header=True, compression='gzip')

# Filter only Male and Female Hosts

In [3]:
Combined = pd.read_csv('Combined_Listings_Gendered.csv.gz', compression='gzip', error_bad_lines=False, low_memory=False)

Listings = Combined[Combined['host_gender'].isin(['male', 'female'])]
Listings['host_gender'].unique()
Listings['host_gender'].value_counts()

female    81352
male      78509
Name: host_gender, dtype: int64

In [11]:
Listings['review_scores_rating'].value_counts()

100.0    37460
98.0     13911
99.0     12344
97.0     11128
96.0      9584
95.0      7812
93.0      6292
94.0      5346
90.0      4378
92.0      3446
80.0      3128
91.0      2861
89.0      1750
87.0      1690
88.0      1631
85.0       896
86.0       823
60.0       754
84.0       732
83.0       569
70.0       313
82.0       286
73.0       269
20.0       261
40.0       181
75.0       171
78.0       166
81.0       165
77.0       150
76.0       145
67.0       111
79.0        79
50.0        70
72.0        62
74.0        54
65.0        43
68.0        40
71.0        40
64.0        22
53.0        20
69.0        14
66.0        14
30.0        12
47.0         9
63.0         9
56.0         8
55.0         8
62.0         5
57.0         2
33.0         2
45.0         2
52.0         1
48.0         1
35.0         1
Name: review_scores_rating, dtype: int64

In [ ]:
Combined = pd.read_csv('Combined_Listings.csv.gz', compression='gzip', error_bad_lines=False, low_memory=False)

host = pd.DataFrame(Combined.loc[:, 'host_name'])
host['name_has_space'] = np.where(host['host_name'].str.contains(' ') , 1, 0)

host['gender'] = host['host_name'].apply(d.get_gender)
#host['gender'] = host['host_name'].apply(d.get_gender, 'usa') ### doesn't make a difference

host.loc[host['name_has_space'] == 1, 'gender'] = 'not_a_name'
Host = host.to_csv ('Host_Name.csv', index = None, header=True)

In [ ]:
data1 = pd.read_csv('All_Listings/Asheville_listings.csv.gz', compression='gzip',
                   error_bad_lines=False)
print(data1.shape)
#data1.insert(0,'Location','Asheville')
#data1.insert(0,'State','NC')
#print(data1.shape)

Combined = data1

def combine(data):
    
    print(data.shape)
    #data.insert(0,'Location', loc)
    #data.insert(0,'State',state)
    #print(data.shape)
    Combined.append(data)
    print(Combined.shape)

In [ ]:
!conda install scrapy

Collecting package metadata (repodata.json): done
Solving environment: /
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - defaults/osx-64::numba==0.38.1=py36h6440ff4_0
  - defaults/osx-64::astropy==3.0.3=py36h1de35cc_2
  - https://repo.continuum.io/pkgs/main/osx-64/datashape-0.5.4-py36hfb22df8_0.tar.bz2/osx-64::datashape==0.5.4=py36hfb22df8_0
  - defaults/osx-64::bokeh==0.13.0=py36_0
  - https://repo.continuum.io/pkgs/main/osx-64/bottleneck-1.2.1-py36hbd380ad_0.tar.bz2/osx-64::bottleneck==1.2.1=py36hbd380ad_0
  - defaults/osx-64::pytest-doctestplus==0.1.3=py36_0
  - defaults/osx-64::pytables==3.4.4=py36h5ca999c_0
  - defaults/osx-64::dask==0.18.1=py36_0
  - defaults/osx-64::matplotlib==2.2.2=py36ha7267d0_0
  - defaults/osx-64::imageio==2.3.0=py36_0
  - https://repo.continuum.io/pkgs/main/osx-64/blaze-0.11.3-py36h02e7a37_0.tar.bz2/osx-64::blaze==0.11.3=py36h02e7a37_0
  - defaults/osx-64::statsmodels==0.9.0=py36h917ab60_0
  - https://repo.continuum.io/pkgs/main/osx-64/scikit-learn-0.19.1-py36hffbff8c_0.tar.bz2/osx-64::scikit-learn==0.19.1=py36hffbff8c_0
  - defaults/osx-64::pytest-astropy==0.4.0=py36_0
  - defaults/osx-64::h5py==2.8.0=py36ha8ecd60_0
  - defaults/osx-64::pandas==0.23.1=py36h1702cab_0
  - https://repo.continuum.io/pkgs/main/osx-64/odo-0.5.1-py36hc1af34a_0.tar.bz2/osx-64::odo==0.5.1=py36hc1af34a_0
  - defaults/osx-64::scikit-image==0.14.0=py36h0a44026_1
  - https://repo.continuum.io/pkgs/main/osx-64/pywavelets-0.5.2-py36h2710a04_0.tar.bz2/osx-64::pywavelets==0.5.2=py36h2710a04_0
  - defaults/osx-64::numexpr==2.6.5=py36h057f876_0
  - defaults/osx-64::scipy==1.1.0=py36hcaad992_0
  - defaults/osx-64::numpy-base==1.14.5=py36ha9ae307_0
  - https://repo.continuum.io/pkgs/main/osx-64/seaborn-0.8.1-py36h595ecd9_0.tar.bz2/osx-64::seaborn==0.8.1=py36h595ecd9_0
  - defaults/osx-64::pytest-arraydiff==0.2=py36_0
  - defaults/osx-64::mkl_random==1.0.1=py36h78cc56f_0
  - defaults/osx-64::mkl_fft==1.0.1=py36h917ab60_0
  - defaults/osx-64::numpy==1.14.5=py36h9bb19eb_0
  - https://repo.continuum.io/pkgs/main/osx-64/bkcharts-0.2-py36h073222e_0.tar.bz2/osx-64::bkcharts==0.2=py36h073222e_0
  - https://repo.continuum.io/pkgs/main/osx-64/patsy-0.5.0-py36_0.tar.bz2/osx-64::patsy==0.5.0=py36_0
/
Warning: >10 possible package resolutions (only showing differing packages):
  - https://repo.continuum.io/pkgs/main/osx-64/conda-env-2.6.0-h36134e3_0.tar.bz2/osx-64::conda-env-2.6.0-h36134e3_0, https://repo.continuum.io/pkgs/main/osx-64/jbig-2.1-h4d881f8_0.tar.bz2/osx-64::jbig-2.1-h4d881f8_0, https://repo.continuum.io/pkgs/main/osx-64/lzo-2.10-h362108e_2.tar.bz2/osx-64::lzo-2.10-h362108e_2, https://repo.continuum.io/pkgs/main/osx-64/osx-64::libntlm-1.4-h1de35cc_2
  - defaults/osx-64::conda-env-2.6.0-h36134e3_0, https://repo.continuum.io/pkgs/main/osx-64/jbig-2.1-h4d881f8_0.tar.bz2/osx-64::jbig-2.1-h4d881f8_0, https://repo.continuum.io/pkgs/main/osx-64/lzo-2.10-h362108e_2.tar.bz2/osx-64::lzo-2.10-h362108e_2, https://repo.continuum.io/pkgs/main/osx-64/osx-64::libntlm-1.4-h1de35cc_2
  - defaults/osx-64::jbig-2.1-h4d881f8_0, https://repo.continuum.io/pkgs/main/osx-64/conda-env-2.6.0-h36134e3_0.tar.bz2/osx-64::conda-env-2.6.0-h36134e3_0, https://repo.continuum.io/pkgs/main/osx-64/lzo-2.10-h362108e_2.tar.bz2/osx-64::lzo-2.10-h362108e_2, https://repo.continuum.io/pkgs/main/osx-64/osx-64::libntlm-1.4-h1de35cc_2
  - defaults/osx-64::conda-env-2.6.0-h36134e3_0, defaults/osx-64::jbig-2.1-h4d881f8_0, https://repo.continuum.io/pkgs/main/osx-64/lzo-2.10-h362108e_2.tar.bz2/osx-64::lzo-2.10-h362108e_2, https://repo.continuum.io/pkgs/main/osx-64/osx-64::libntlm-1.4-h1de35cc_2
  - defaults/osx-64::jbig-2.1-h4d881f8_0, defaults/osx-64::libntlm-1.4-h1de35cc_2, https://repo.continuum.io/pkgs/main/osx-64/conda-env-2.6.0-h36134e3_0.tar.bz2/osx-64::conda-env-2.6.0-h36134e3_0, https://repo.continuum.io/pkgs/main/osx-64/lzo-2.10-h362108e_2.tar.bz2/osx-64::lzo-2.10-h362108e_2
  - defaults/osx-64::conda-env-2.6.0-h36134e3_0, defaults/osx-64::jbig-2.1-h4d881f8_0, defaults/osx-64::libntlm-1.4-h1de35cc_2, https://repo.continuum.io/pkgs/main/osx-64/lzo-2.10-h362108e_2.tar.bz2/osx-64::lzo-2.10-h362108e_2
  - defaults/osx-64::libntlm-1.4-h1de35cc_2, https://repo.continuum.io/pkgs/main/osx-64/conda-env-2.6.0-h36134e3_0.tar.bz2/osx-64::conda-env-2.6.0-h36134e3_0, https://repo.continuum.io/pkgs/main/osx-64/jbig-2.1-h4d881f8_0.tar.bz2/osx-64::jbig-2.1-h4d881f8_0, https://repo.continuum.io/pkgs/main/osx-64/lzo-2.10-h362108e_2.tar.bz2/osx-64::lzo-2.10-h362108e_2
  - defaults/osx-64::conda-env-2.6.0-h36134e3_0, defaults/osx-64::libntlm-1.4-h1de35cc_2, https://repo.continuum.io/pkgs/main/osx-64/jbig-2.1-h4d881f8_0.tar.bz2/osx-64::jbig-2.1-h4d881f8_0, https://repo.continuum.io/pkgs/main/osx-64/lzo-2.10-h362108e_2.tar.bz2/osx-64::lzo-2.10-h362108e_2
  - defaults/osx-64::libntlm-1.4-h1de35cc_2, defaults/osx-64::lzo-2.10-h362108e_2, https://repo.continuum.io/pkgs/main/osx-64/conda-env-2.6.0-h36134e3_0.tar.bz2/osx-64::conda-env-2.6.0-h36134e3_0, https://repo.continuum.io/pkgs/main/osx-64/jbig-2.1-h4d881f8_0.tar.bz2/osx-64::jbig-2.1-h4d881f8_0
  - defaults/osx-64::lzo-2.10-h362108e_2, https://repo.continuum.io/pkgs/main/osx-64/conda-env-2.6.0-h36134e3_0.tar.bz2/osx-64::conda-env-2.6.0-h36134e3_0, https://repo.continuum.io/pkgs/main/osx-64/jbig-2.1-h4d881f8_0.tar.bz2/osx-64::jbig-2.1-h4d881f8_0, https://repo.continuum.io/pkgs/main/osx-64/osx-64::libntlm-1.4-h1de35cc_2
  ... and othedone

## Package Plan ##

  environment location: /anaconda3

  added / updated specs:
    - scrapy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _r-mutex-1.0.0             |      anacondar_1           2 KB
    matplotlib-3.0.0           |   py36h54f8f79_0         6.8 MB
    rstudio-1.1.383            |       h4814094_2        30.0 MB
    tbb-2019.8                 |       h04f5b5a_0         166 KB
    tbb4py-2019.8              |   py36h04f5b5a_0          64 KB
    ------------------------------------------------------------
                                           Total:        37.1 MB

The following NEW packages will be INSTALLED:

  tbb                pkgs/main/osx-64::tbb-2019.8-h04f5b5a_0
  tbb4py             pkgs/main/osx-64::tbb4py-2019.8-py36h04f5b5a_0

The following packages will be UPDATED:

  matplotlib                           2.2.2-py36ha7267d0_0 --> 3.0.0-py36h54f8f79_0

The following packages will be DOWNGRADED:

  _r-mutex                                                  -->
  rstudio                                1.1.423-hb125a76_0 --> 1.1.383-h4814094_2


Proceed ([y]/n)?

In [ ]:
y

In [3]:
May_Reviews = pd.read_csv('Combined_Reviews_May20.csv.gz', compression='gzip', error_bad_lines=False,\
                          parse_dates=['review_created_at'],
                          dtype={'reviewee_id':str,'review_id': str,'reviewer_id':str,'listing_id':str})

In [4]:
May_Reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10720558 entries, 0 to 10720557
Data columns (total 18 columns):
 #   Column                 Dtype
---  ------                 -----
 0   listing_id             object
 1   reviews_count          int64
 2   reviewee_deleted       bool
 3   reviewee_first_name    object
 4   reviewee_host_name     object
 5   reviewee_id            object
 6   reviewee_is_superhost  bool
 7   review_id              object
 8   review_created_at      datetime64[ns, UTC]
 9   review_language        object
 10  review_rating          float64
 11  review_comments        object
 12  host_response          object
 13  reviewer_deleted       bool
 14  reviewer_first_name    object
 15  reviewer_host_name     object
 16  reviewer_id            object
 17  reviewer_is_superhost  bool
dtypes: bool(4), datetime64[ns, UTC](1), float64(1), int64(1), object(11)
memory usage: 1.2+ GB

In [5]:
May_Reviews.head()

,listing_id,reviews_count,reviewee_deleted,reviewee_first_name,reviewee_host_name,reviewee_id,reviewee_is_superhost,review_id,review_created_at,review_language,review_rating,review_comments,host_response,reviewer_deleted,reviewer_first_name,reviewer_host_name,reviewer_id,reviewer_is_superhost
0,19137905,50,False,Tamara,Tamara,107292420.0,False,562159788.0,2019-11-10 18:34:12+00:00,en,4.0,The accommodations were very clean and comfort...,NaN,False,Kathy,Kathy,210298195.0,False
1,19137905,50,False,Tamara,Tamara,107292420.0,False,559161145.0,2019-11-03 21:10:52+00:00,en,5.0,Very clean and pleasant quarters. Her dog is ...,NaN,False,Scott,Scott,119171421.0,False
2,19137905,50,False,Tamara,Tamara,107292420.0,False,551751582.0,2019-10-20 19:14:22+00:00,en,5.0,"Tamara was an excellent host, and Kinzee the a...",NaN,False,Maggie,Maggie,155606721.0,False
3,19137905,50,False,Tamara,Tamara,107292420.0,False,547102183.0,2019-10-14 18:45:18+00:00,en,5.0,"Absolute best value in the area, amazing littl...",NaN,False,Colton,Colton,266853043.0,False
4,19137905,50,False,Tamara,Tamara,107292420.0,False,542485908.0,2019-10-06 17:40:52+00:00,en,4.0,"Flexible host with check out time. Very clean,...",NaN,False,Rohit,Rohit,160009185.0,False

In [6]:
All_Listings = pd.read_csv('Listings_March_Merged.csv.gz', compression='gzip', error_bad_lines=False)

C:\Users\s137c989\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (14,27,30,31,117) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [8]:
All_Listings.head()

,Unnamed: 0,listing_id,room_and_property_type,price,person_capacity,bathrooms,bedrooms,beds,min_nights,max_nights,...,Topic_30_22,Topic_30_23,Topic_30_24,Topic_30_25,Topic_30_26,Topic_30_27,Topic_30_28,Topic_30_29,Topic_30_30,zipcode
0,0,9214018,Entire house,1000.0,10,3.5,4.0,4.0,30,1125,...,0.001101,0.002915,0.001955,0.002376,0.002321,0.002022,0.001395,0.001989,0.102754,92663
1,1,21109067,Entire house,1025.0,10,5.5,4.0,4.0,3,1125,...,0.000195,0.000517,0.000346,0.000421,0.000411,0.071750,0.000247,0.000353,0.056638,90742
2,2,13301958,Entire house,1000.0,10,5.5,5.0,5.0,31,1125,...,0.013019,0.000991,0.000664,0.000807,0.000789,0.115257,0.000474,0.000676,0.037100,92657
3,3,30481280,Entire villa,1000.0,10,5.5,5.0,5.0,60,1125,...,0.005508,0.014587,0.009783,0.011888,0.011611,0.010118,0.006981,0.009954,0.009376,92603
4,4,18315194,Entire townhouse,1000.0,15,4.0,6.0,9.0,2,27,...,0.019194,0.000547,0.000367,0.000446,0.000436,0.000379,0.000262,0.000373,0.000352,92663

In [9]:
All_Listings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230705 entries, 0 to 230704
Columns: 118 entries, Unnamed: 0 to zipcode
dtypes: bool(4), float64(62), int64(20), object(32)
memory usage: 201.5+ MB